export enum Cor {
  Vermelho = 'VERMELHO',
  Azul = 'AZUL',
  Verde = 'VERDE',
  Preto = 'PRETO',
  Branco = 'BRANCO',
  Amarelo = 'AMARELO',
  Rosa = 'ROSA',
  Roxo = 'ROXO',
  Laranja = 'LARANJA',
  Marrom = 'MARROM',
  Cinza = 'CINZA',
  Bege = 'BEGE',
  Dourado = 'DOURADO',
  Prateado = 'PRATEADO',
  Vinho = 'VINHO',
  Nude = 'NUDE',
  Transparente = 'TRANSPARENTE',
  Outro = 'OUTRO'
}